In [1]:
import warnings
warnings.filterwarnings('ignore')

from IPython.core.display import display, HTML
display(HTML('<style>.container {width: 90% !important; }</style>'))

In [6]:
import sys
sys.path.append("/simpsom/")
import simpsom as sps 
# import simpsom as sps
import random
import numpy as np
random.seed(42)
np.random.seed(42)

In [46]:
# data = np.random.rand(10,2)
data = [[ 0.80,  0.55,  0.22,  0.03],
        [ 0.82,  0.50,  0.23,  0.03],
        [ 0.80,  0.54,  0.22,  0.03],
        [ 0.80,  0.53,  0.26,  0.03],
        [ 0.79,  0.56,  0.22,  0.03],
        [ 0.75,  0.60,  0.25,  0.03],
        [ 0.77,  0.59,  0.22,  0.03]]  
print(data)

[[0.8, 0.55, 0.22, 0.03], [0.82, 0.5, 0.23, 0.03], [0.8, 0.54, 0.22, 0.03], [0.8, 0.53, 0.26, 0.03], [0.79, 0.56, 0.22, 0.03], [0.75, 0.6, 0.25, 0.03], [0.77, 0.59, 0.22, 0.03]]


In [47]:
net = sps.SOMNet(3, 3, data, topology='hexagonal', 
                init='pca', metric='euclidean',
                neighborhood_fun='gaussian', PBC=False,
                random_seed=32, GPU=False, CUML=False,
                output_path="./")

net.train(train_algo='online', start_learning_rate=0.01, epochs=5)

2023-04-06 15:11:15.823 | INFO     | simpsom.network:__init__:115 - Hexagonal topology.
2023-04-06 15:11:15.824 | WARNING  | simpsom.network:_set_weights:179 - Please be sure that the data have been standardized before using PCA.
2023-04-06 15:11:15.825 | INFO     | simpsom.network:_set_weights:181 - The weights will be initialized with PCA.
2023-04-06 15:11:15.827 | INFO     | simpsom.network:train:375 - The map will be trained with the online algorithm.
2023-04-06 15:11:15.827 | WARNING  | simpsom.network:_randomize_dataset:277 - Epochs for online training are less than the input datapoints.


In [48]:
for node in net.nodes_list:
    print(node.weights)

[-6.1126620e-01 -7.1314120e-01 -1.5406580e-01  1.4586493e-04]
[-4.3798697e-01 -5.7064813e-01 -4.9556274e-02  3.3051646e-04]
[-2.7282202e-01 -6.4472753e-01 -4.9174413e-02  1.4586493e-04]
[-3.3438033e-01 -6.7998415e-01 -1.4952579e-01  4.3702321e-04]
[-2.2426337e-01 -7.8332961e-01 -1.4751785e-01  7.7221240e-04]
[-6.6734439e-01 -7.8555048e-01 -2.2821736e-01  4.3702321e-04]
[-0.04201955 -0.49922147 -0.05900617  0.00077221]
[ 0.34853822 -0.5458952  -0.02848397  0.00103195]
[ 0.3367322  -0.70598775 -0.03299545  0.00077221]


In [54]:
net = sps.SOMNet(3, 3, data, topology='hexagonal', 
                init='random', metric='euclidean',
                neighborhood_fun='gaussian', PBC=False,
                random_seed=32, GPU=False, CUML=False,
                output_path="./")

net.train(train_algo='batch', start_learning_rate=0.01, epochs=5, batch_size=1)

2023-04-06 15:39:44.566 | INFO     | simpsom.network:__init__:115 - Hexagonal topology.
2023-04-06 15:39:44.567 | INFO     | simpsom.network:_set_weights:192 - The weights will be initialized randomly.
2023-04-06 15:39:44.570 | INFO     | simpsom.network:train:375 - The map will be trained with the batch algorithm.


In [55]:
for node in net.nodes_list:
    print(node.weights)

[0.793797   0.54255027 0.24599402 0.03      ]
[0.80092543 0.53488255 0.23439065 0.02999999]
[0.8056613  0.52978873 0.226682   0.03      ]
[0.78007686 0.5652668  0.23830524 0.03      ]
[0.7913148  0.55182415 0.22992602 0.03      ]
[0.79917854 0.5424176  0.22406264 0.03      ]
[0.7692252  0.58235025 0.23427145 0.03      ]
[0.78151995 0.5672675  0.22837429 0.03      ]
[0.7927453  0.5534966  0.22299007 0.03      ]


In [4]:
from xpysom import XPySom    

In [56]:
som = XPySom(3, 3, 4, sigma=0.3, learning_rate=0.5, random_seed=42) # initialization of 6x6 SOM
som.train_batch(data, 5) # trains the SOM with 5 iterations

In [58]:
som.get_weights()

array([[[0.7799992 , 0.5750006 , 0.22000095, 0.03      ],
        [0.7900001 , 0.5599999 , 0.2200001 , 0.03      ],
        [0.79666704, 0.549999  , 0.22000022, 0.03      ]],

       [[0.7693206 , 0.59024334, 0.2211894 , 0.03      ],
        [0.79189175, 0.5539381 , 0.22818556, 0.03      ],
        [0.80037695, 0.5441348 , 0.22022249, 0.03      ]],

       [[0.7525488 , 0.59708697, 0.24927172, 0.03      ],
        [0.7988696 , 0.5315783 , 0.25837886, 0.03      ],
        [0.81789196, 0.5042159 , 0.23035134, 0.03      ]]], dtype=float32)